#%RAML 1.0 Trait

headers: 
  Content-Type:
    type: string
    example: application/json
  Authorization:
    type: string
    example: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2YTdlYWNhYi0yZDU5LTMxYzktYjJiMC1lMTc1NGZlZDc0YWMiLCJyb2xlIjoiUEFPX0FETUlOIiwiZXhwIjoxNTY1OTExNzE5fQ.Q8Fj3caCiBEN9syYxt7Z5mDsKKY5MRyfY2wTTG3yIrqATovNHS69tF4fTGs3REeqYySjKs6wDRwZSmptXY2iOw
