# Use an official OpenJDK runtime as a parent image
FROM gradle:5.5.1-jdk11

# Set the working directory to /app
WORKDIR /application

EXPOSE 8080

# Run jar file when the container launches
CMD ["gradle", "bootRun", "--args='--spring.profiles.active=dev'"]